### ISSUE TITLE
docker: Error response from daemon: Cannot link to a non running container: /sonerezh-db AS /sonerezh-app/sonerezh-db

### ISSUE THREAD

**Issue by avma** [Sonerezh/sonerezh#325]
[https://www.sonerezh.bzh/docs/en/installation.html#installation-with-docker](url)

Hi,

Following the install section ( [https://www.sonerezh.bzh/docs/en/installation.html#installation-with-docker](url)), using docker on a raspberry pi. After running: 
`sudo docker run --name sonerezh-app --link sonerezh-db:sonerezh-db \
                              --volume /path/to/music:/mnt/media/music/mymusic \
                              --volume /path/to/thumbnails:/mnt/sonerezh/thumbnails \
                               --detach --publish 8080:80 \
                               sonerezh/sonerezh:latest` 
I'm getting this error message: docker: Error response from daemon: 
> 
Cannot link to a non running container: /sonerezh-db AS /sonerezh-app/sonerezh-db.
> 

It looks like I'm missing somthing but cant figure it out...
Thank you for your help
Avi

**Comment by snow3461** [comment]
Hi, not dev, but you need to run a mariaDB container too. See [Sonerezh Docs](https://www.sonerezh.bzh/docs/en/installation.html)

**Comment by PixiBixi** [comment]
Indeed, you must to run a mariadb container before to run your sonerezh container.

I use the official image, this is my docker-compose.yml for mariadb:

```yaml
  sonerezh-db:
    image: mariadb:10
    container_name: sonerezh-db
    restart: always
    volumes:
      - /my/path/to/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=whatyouwant
      - MYSQL_DATABASE=sonerezh
      - MYSQL_USER=sonerezh
      - MYSQL_PASSWORD=whatyouwant
```
